---

- name: Create nginx repository
  template: src=nginx.repo.j2
          dest=/etc/yum.repos.d/nginx.repo

- name: Install nginx
  yum: pkg=nginx
       state=present

- name: Enable and start nginx
  service: name=nginx
           enabled=yes
           state=started

