---

- name: Create nginx repository
  template: src=nginx.repo.j2
          dest=/etc/yum.repos.d/nginx.repo

- name: Install nginx
  yum: pkg=nginx
       state=present

- name: Enable and start nginx
  service: name=nginx
           enabled=yes
           state=started

- name: Disable default website
  command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.disabled
           creates=/etc/nginx/conf.d/default.conf.disabled
           removes=/etc/nginx/conf.d/default.conf
  notify: Restart nginx

