---

- hosts: rails
  remote_user: root
  roles:
    - { role: selinux, tags: selinux }
    - { role: cron, tags: cron }
    - { role: timezone, tags: timezone }
    - { role: chrony, tags: chrony }
    - { role: git, tags: git }
    - { role: root_password, tags: root_password }
    - { role: ssh, tags: ssh }
    - { role: firewalld, tags: firewalld }
    - { role: unneeded_services, tags: unneeded_services }
    - { role: ipv6, tags: ipv6 }
    - { role: user, tags: user_app, name: app, comment: "Application user" }
    - { role: user, tags: user_anthony, name: anthony, comment: "Anthony Candaele" }
    - { role: nginx, tags: nginx }
    - { role: mariadb, tags: mariadb }
    - { role: nodejs, tags: nodejs }
    - { role: ruby, tags: ruby_app, user: app, version: 2.2.4 }
    - { role: myapp, tags: myapp }
