---

- name: Disable IPv6
  sysctl: name={{ item }}
          value=1
          reload=yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

- name: Disable IPv6 support for chronyd
  copy: dest=/etc/sysconfig/chronyd
        content="OPTIONS='-4'"
  notify: Restart chronyd
